const types = {
  SIGN_OUT: "SIGN_OUT",
  SIGN_IN: "SIGN_IN",
  FETCH_STREAM: "FETCH_STREAM",
  FETCH_STREAMS: "FETCH_STREAMS",
  CREATE_STREAM: "CREATE_STREAM",
  DELETE_STREAM: "DELETE_STREAM",
  LIST_STREAM: "LIST_STREAM",
  UPDATE_STREAM: "UPDATE_STREAM",
};

export default types;
